version: '3.8'

services:
  todo:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
    restart: 'always'
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: passw0rd
    ports:
      - '8080:8080'
  db:
    image: postgres:13.3
    restart: 'always'
    environment:
      POSTGRES_DB: 'todo'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw0rd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      retries: 120
    ports:
      - '5432:5432'